return {
    Name = "Dark",

    Notification = Color3.fromRGB(61, 57, 70),
    NotificationBorder = Color3.fromRGB(222, 208, 255),
    NotificationTitle = Color3.fromRGB(218, 213, 233),

    Top = Color3.fromRGB(10, 10, 10),
    TopTitle = Color3.fromRGB(255, 255, 255),
    TopDescription = Color3.fromRGB(255, 255, 255),
    TopTransparency = 0.1,
    TopHoverTransparency = 0,

    Indicator = Color3.fromRGB(138, 104, 253),
    TabSelected = Color3.fromRGB(255, 255, 255),
    TabNotSelected = Color3.fromRGB(163, 148, 209),
    TabHover = Color3.fromRGB(46, 41, 59),
    TabSoundHoverId = "rbxassetid://7147619379",
    TabSoundHoverVolume = 0.04,
    TabSoundClickId = "rbxassetid://18215157567",
    TabSoundClickVolume = 5,

    Container = Color3.fromRGB(49, 47, 57),
    ContainerFade = Color3.fromRGB(48, 46, 56),

    HeaderTitle = Color3.fromRGB(255, 255, 255),
    HeaderDescription = Color3.fromRGB(224, 219, 240),

    SearchBoxPlaceholder = Color3.fromRGB(147, 142, 162),
    SearchBoxText = Color3.fromRGB(254, 254, 254),

    Element = Color3.fromRGB(44, 42, 51),
    ElementText = Color3.fromRGB(217, 212, 232),
    ElementTransparency = 0,
    ElementBorder = Color3.fromRGB(99, 75, 172),
    ElementSoundHoverId = "rbxassetid://125236580407249",
    ElementSoundHoverVolume = 2,
    ElementSoundClickId = "rbxassetid://139719503904449",
    ElementSoundClickVolume = 10,
    ElementFade = Color3.fromRGB(128, 94, 233),

    SectionText = Color3.fromRGB(255, 255, 255),

    Paragraph = Color3.fromRGB(69, 61, 92),
    ParagraphText = Color3.fromRGB(224, 219, 240),
    ParagraphTransparency = 0,

    ToggleSlider = Color3.fromRGB(128, 94, 233),
    ToggleBorder = Color3.fromRGB(103, 77, 179),
    ToggleOnColor = Color3.fromRGB(127, 93, 232),
    ToggleHoverColor = Color3.fromRGB(140, 102, 255),
    ToggleOffColor = Color3.fromRGB(102, 76, 178),

    DropdownSelected = Color3.fromRGB(102, 76, 178),
    DropdownBorder = Color3.fromRGB(140, 102, 254),
    DropdownText = Color3.fromRGB(249, 249, 249),
    DropdownImage = Color3.fromRGB(255, 255, 255),
    DropdownImageId = "rbxassetid://120679435135651",
    Item = Color3.fromRGB(61, 57, 70),
    ItemText = Color3.fromRGB(252, 252, 252),
    ItemHold = Color3.fromRGB(102, 76, 178),
    ItemHoldArrow = Color3.fromRGB(37, 35, 45),

    SliderText = Color3.fromRGB(250, 250, 250),
    SliderTrack = Color3.fromRGB(37, 35, 43),
    SliderFill = Color3.fromRGB(103, 77, 179),
    SliderDot = Color3.fromRGB(128, 94, 233),
    SliderHold = Color3.fromRGB(139, 101, 253),
    SliderDotHold = Color3.fromRGB(140, 102, 255),

    InputPlaceholder = Color3.fromRGB(147, 142, 162),
    InputText = Color3.fromRGB(254, 254, 254),
    InputBorder = Color3.fromRGB(139, 101, 253),

    Button = Color3.fromRGB(90, 52, 205),
    ButtonText = Color3.fromRGB(218, 213, 233),
    ButtonSoundHoverId = "rbxassetid://7147619379",
    ButtonSoundHoverVolume = 0.04,
    ButtonSoundClickId = "rbxassetid://18215157567",
    ButtonSoundClickVolume = 5,
}
